FROM python:3.11

WORKDIR /code

# Atualização necessária: Instalar o ffmpeg para o processamento do áudio
RUN apt-get update && apt-get install -y ffmpeg

COPY ./requirements.txt /code/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

COPY ./app /code/app

EXPOSE 8080

CMD ["uvicorn", "app.main:app", "--proxy-headers", "--host", "0.0.0.0", "--port", "8080"]